---
- name: build new hypervisor
  hosts: hypervisor
  become: yes
  gather_facts: yes
  roles: 
  - role: nick.platform.libvirt_host
  - role: nick.platform.libvirt_storage
  - role: nick.platform.libvirt_net_public
  - role: nick.platform.libvirt_net_private
    vars: 
      lab_stuff: site1_stuff
  - role: nick.platform.libvirt_net_private
    vars: 
      lab_stuff: site2_stuff

# json_query requires jmespath install
# see comments in 
# hostvars/monitor.lab.example.com/main.yml
