---
# The "gateway" machine has two interfaces, one on the home network and one on the new libvirt network.
# There is no DHCP yet so the second interface is assigned an IP address.
# Use a kickstart file to set up this networking.

# !!! issues with routing table 
#   [nick@gateway ~]$ ip route
#   default via 192.168.1.254 dev enp1s0 proto dhcp src 192.168.1.3 metric 100 
#   default via 192.168.135.1 dev enp2s0 proto static metric 101 
#   192.168.1.0/24 dev enp1s0 proto kernel scope link src 192.168.1.3 metric 100 
#   192.168.135.0/24 dev enp2s0 proto kernel scope link src 192.168.135.3 metric 101 
#   [nick@gateway ~]$ 
# extra default 
# routes to other boxes missing 


- name: add image facts to hostvars
  hosts: gateway
  become: true
  gather_facts: false
  roles:
    - name: "check for existing images"
      role: nick.platform.libvirt_image_facts
      delegate_to: "{{ groups['hypervisor'][0] }}"



# If there already is an image file, don't trash it. 
- name: Kickstart a new machine
  hosts: gateway
  become: true
  gather_facts: false
  serial: 1
  pre_tasks:
    - name: don't overwrite anything
      meta: end_host
      when: volume_image_file_exists
  roles:
    - name: "kickstart the VM on hypervisor {{ groups['hypervisor'][0] }}"
      role: nick.platform.libvirt_machine_kickstart
      delegate_to: "{{ groups['hypervisor'][0] }}"
    - name: "update /etc/hosts on install host {{ groups['install_host'][0] }}"
      role: nick.platform.hosts_record
      vars:
        ip_address: "{{ nics[1]['ip'] }}"
      delegate_to: "{{ groups['install_host'][0] }}"


- name: Start new server machine
  hosts: gateway
  become: true
  gather_facts: false
  serial: 1
  roles:
    - name: "run machine (it stops after install)"
      role: nick.platform.libvirt_machine_start
      delegate_to: "{{ groups['install_host'][0] }}"
      when: volume_image_file_exists


# If there is no base file, assume configuration didn't complete and 
# we are good to go again.
- name: Configure new server machine
  hosts: gateway
  become: true
  gather_facts: false
  serial: 1
  vars_files:
    - vault-credentials.yml
  pre_tasks:
    - name: "base image exists, not carrying on"
      ansible.builtin.meta: end_host
      when: volume_base_file_exists
    - ansible.builtin.setup:

  roles:
    - role: nick.platform.managed_node
    - name: "tell gateway the ipa server address is {{ lab_net_prefix }}.3"
      role: nick.platform.hosts_record
      # !!! hardcoded
      vars:
        ip_address: "{{ lab_net_prefix }}.5"
        fqdn: id.lab.example.com
        host: id
    - role: nick.platform.dns_record
      vars:
        zone_forward_name: "{{ lab_domain_forward }}"
        # remove domain, leave host and maybe subdomain
        # !!! hardcoded
        record_a_name: "{{ inventory_hostname | regex_replace('.lab.example.com') }}"
        record_a_value: "{{ nics[1]['ip'] }}"
        zone_reverse_name: "{{ lab_domain_reverse }}"
        # use the last octet only
        record_ptr_name: "{{ nics[1]['ip'].split('.')[3] }}"
        # DNS is fussy about root domain '.'
        record_ptr_value: "{{ inventory_hostname + '.' }}"
    - role: nick.platform.cdn_repo_consumer
    - role: nick.platform.latest_packages
    - role: nick.platform.server_cert
    - role: nick.platform.smtp_client
    - role: nick.platform.squid_proxy
    - role: nick.platform.dns_forwarder


- name: Keep image and config of the new machine
  hosts: gateway
  become: true
  gather_facts: false
  serial: 1
    
  pre_tasks:
    - name: "don't overwrite anything"
      ansible.builtin.meta: end_host
      when: volume_image_file_exists

  roles:
    # create $FQDN-base.qcow2 image and $FQDN.xml config.
    # if the $FQDN-base.qcow2 file already exists, this role does not change anything. 
    - name: "copy the volume file and config, then delete the machine"
      role: nick.platform.libvirt_machine_image
      delegate_to: "{{ groups['hypervisor'][0] }}"
