---
# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/providing-dhcp-services_networking-infrastructure-services#doc-wrapper

# controlplane.site1.example.com
# The machine has one interface on the private libvirt network.
# It uses gateway as a web proxy.
# it hosts an AAP2 controller.

# Use a kickstart file to install and configure the OS.

- name: Kickstart a new machine
  hosts: automationcontroller
  become: true
  gather_facts: false
  serial: 1
  roles:
    - name: "kickstart the VM on hypervisor {{ groups['hypervisor'][0] }}"
      role: nick.platform.libvirt_machine_kickstart
      delegate_to: "{{ groups['hypervisor'][0] }}"
    - name: "update /etc/hosts on install host {{ groups['install_host'][0] }}"
      role: nick.platform.hosts_record
      vars:
        ip_address: "{{ address[inventory_hostname]['ipv4'] }}"
      delegate_to: "{{ groups['install_host'][0] }}"
    - name: "run machine (it stops after install)"
      role: nick.platform.libvirt_machine_start
      delegate_to: "{{ groups['install_host'][0] }}"


- name: Configure new server machine
  hosts: automationcontroller
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - vault-rhsm.yml
  environment:
    http_proxy: http://gateway.lab.example.com:3128
    HTTPS_PROXY: http://gateway.lab.example.com:3128
    no_proxy: localhost,127.0.0.1,example.com
  roles:
    - nick.platform.managed_node
    - nick.platform.cdn_repo_consumer
    - nick.platform.latest_packages
    - nick.platform.server_cert
    - nick.platform.smtp_client


- name: Keep image and config of the new machine
  hosts: automationcontroller
  become: true
  gather_facts: false
  serial: 1
  roles:
    # create $FQDN-base.qcow2 image and $FQDN.xml config.
    # if the $FQDN-base.qcow2 file already exists, this role does not change anything.
    - name: "copy the volume file and config, then delete the machine"
      role: nick.platform.libvirt_machine_image
      delegate_to: "{{ groups['hypervisor'][0] }}"
