---
- name: build new hypervisor
  hosts: hypervisor
  become: true
  gather_facts: true
  roles:
    - role: nick.platform.libvirt_host
    - role: nick.platform.libvirt_storage
    - role: nick.platform.libvirt_net_public
    - role: nick.platform.libvirt_net_private
