= Ansible playbook for turning a PC into a set of Ansible Automation Platform VMs

Ansible helps me build my home lab. 
This playbook turns a PC running RHEL 9 into a hypervisor running a pile-load (that's the technical term) of Virtual Machines. 
Each VM runs a set of services that support my home lab. 

Idea is to build the 
Ansible Automation Platform 2
Reference Architecture. 

https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index#doc-wrapper


Under construction. Sections marked with !!! and ??? are notes to self. 

* *controlplane-1*, a control plane node in the Automation Controller cluster
* *controlplane-2*, a control plane node in the Automation Controller cluster
* *controlplane-3*, a control plane node in the Automation Controller cluster

==  requirements 

Various roles and collections. 
See the cheatsheet below. 


== the KVM/QEMU hypervisor 

A bootstrap shell script kicks off the install. 
See instructions in 
https://github.com/nickhardiman/ansible-playbook-lab/blob/main/machine-hypervisor.sh[machine-hypervisor.sh]


== VMs 

