= Ansible playbook for turning a PC into a set of Ansible Automation Platform VMs

Ansible helps me build my home lab. 
This playbook turns a PC running RHEL 9 into a hypervisor running a pile-load (that's the technical term) of Virtual Machines. 
Each VM runs a set of services that support my home lab. 

Idea is to build the 
Ansible Automation Platform 2
Reference Architecture. 

https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index#doc-wrapper


Under construction. Sections marked with !!! and ??? are notes to self. 

. *gateway*, a proxy with interfaces on the public and private networks. Also provides utilities.
. *controlplane-1*, a control plane node in the Automation Controller cluster
. *controlplane-2*
. *controlplane-3*
. *controlplane-db*, a Postgres database for the Automation Controller
. *automationhub-1*, a hub node in the Private Automation Hub cluster. This mounts an NFS share from gateway.
. *automationhub-2*
. *automationhub-3*
. *automationhub-db*, a Postgres database for the Private Automation Hub
. *executionnode-1*, an execution plane node 
. *executionnode-2*


==  requirements 

Various roles and collections. 
See the cheatsheet below. 


== the KVM/QEMU hypervisor 

A bootstrap shell script kicks off the install. 
See instructions in 
https://github.com/nickhardiman/ansible-playbook-lab/blob/main/machine-hypervisor.sh[machine-hypervisor.sh]


== VMs 


The https://github.com/nickhardiman/ansible-playbook-aap2-refarch/blob/main/group_vars/all/main.yml[defaults file] defines a lot of values. 
For instance, most 
MAC addresses are set to ** 52:54:00:04:00:* **,  and 
IPv4 addresses are set to ** 192.168.136.* **. 
Check out DHCP's 
https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/dhcp_server/templates/dhcpd.conf.j2[config].

.guests attached to bridges
[%header,format=csv]
|===
name,         interface, MAC,               IP,              domain
*netpublic0*,    *brpublic0*,    52:54:00:03:00:01, 192.168.1.1,     site1.home
gateway,      enp1s0,    52:54:00:03:00:03, 192.168.1.3,     site1.home

*netlab0*,  *brlab0*,   52:54:00:04:00:01, 192.168.136.1,   site1.lab.example.com
 ,           ,           52:54:00:04:00:02, 192.168.136.2,   site1.lab.example.com
gateway,          enp2s0,    52:54:00:04:00:03, 192.168.136.3,   site1.lab.example.com
controlplane-1,   enp1s0,    52:54:00:04:00:10, 192.168.136.10,   site1.lab.example.com
controlplane-2,   enp1s0,    52:54:00:04:00:11, 192.168.136.11,   site1.lab.example.com
controlplane-3,   enp1s0,    52:54:00:04:00:12, 192.168.136.12,   site1.lab.example.com
controlplane-db,  enp1s0,    52:54:00:04:00:13, 192.168.136.13,   site1.lab.example.com
               ,  enp1s0,    52:54:00:04:00:14, 192.168.136.14,   site1.lab.example.com
executionnode-1,  enp1s0,    52:54:00:04:00:15, 192.168.136.15,   site1.lab.example.com
executionnode-2,  enp1s0,    52:54:00:04:00:16, 192.168.136.16,   site1.lab.example.com
automationhub-1,  enp1s0,    52:54:00:04:00:17, 192.168.136.17,   site1.lab.example.com
automationhub-2,  enp1s0,    52:54:00:04:00:18, 192.168.136.18,   site1.lab.example.com
automationhub-3,  enp1s0,    52:54:00:04:00:19, 192.168.136.19,   site1.lab.example.com
automationhub-db, enp1s0,    52:54:00:04:00:20, 192.168.136.20,   site1.lab.example.com
                , enp1s0,    52:54:00:04:00:21, 192.168.136.21,   site1.lab.example.com
|===


== cheatsheet 

AAP install 

manual instructions
 https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index

quite a bit to do 

* get install bundle
* inventory, credentials vault (see files)
* firewall ports 
* create NFS share on gateway 

[source,shell]
....
# https://www.redhat.com/sysadmin/configure-nfs-linux
systemctl enable --now nfs-server
dnf install nfs-utils
systemctl enable --now rpcbind
mkdir -p /var/nfs/exports/pulp
chown root:ansible_user /var/nfs/exports/pulp 
chmod 775 root:ansible_user /var/nfs/exports/pulp 
echo '/var/nfs/exports/pulp 192.168.0.0/16(rw,no_root_squash)' >> /etc/exports
exportfs -r
firewall-cmd --add-service nfs --permanent
firewall-cmd --add-service nfs
....

* create NFS mount on hubs 

[source,shell]
....
sudo mkdir /var/lib/pulp
dnf install nfsv4-client-utils.x86_64
mount -v -t nfs4 192.168.136.3:/var/nfs/exports/pulp /var/lib/pulp
....

* ??? add proxy env vars for hubs to download containers
* !!! no, maybe login is non-interactive. /etc/environment?
* ??? add proxy env vars for controller to download manifest
*     in /etc/profile.d/http_proxy.sh 


* copy files/credentials-controlplane-plaintext.yml to credentials-controlplane.yml 
* add sensitive details
* encrypt
*  Install controller.

[source,shell]
....
ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/ansible-key.priv \
ANSIBLE_REMOTE_USER=ansible_user \
ANSIBLE_BECOME=True \
ANSIBLE_HOST_KEY_CHECKING=False \
./setup.sh -e @credentials-controlplane.yml --  \
  --vault-pass-file=~/vault-password.txt
....

* copy files/credentials-hub-plaintext.yml, add sensitive details, encrypt
*  Install hub. 
 proxy settings are for internet downloads of container images. 
 Installer doesn't download collections.

[source,shell]
....
ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/ansible-key.priv \
ANSIBLE_REMOTE_USER=ansible_user \
ANSIBLE_BECOME=True \
ANSIBLE_HOST_KEY_CHECKING=False \
./setup.sh \
 -e @credentials_hub.yml \
 -e 'http_proxy=http://gateway.site1.lab.example.com:3128' \
 -e 'https_proxy=http://gateway.site1.lab.example.com:3128' \
 -e 'no_proxy=localhost,127.0.0.1,example.com' \
 --  \
 --vault-pass-file=~/vault-password.txt
....

