- name: Configure AAP server certificate
  hosts: install_host
  become: true
  gather_facts: false
  vars_files:
    - ~/vault-credentials.yml
    
  roles:
    - role: nick.platform.server_cert
      vars:
        server_cn: no-san.site1.example.com

    - role: nick.platform.server_cert
      vars:
        server_cn: controlplane.site1.example.com
        subject_alt_name:
          - DNS:controlplane-1.site1.example.com
          - DNS:controlplane-2.site1.example.com
          - DNS:controlplane-3.site1.example.com
# check with
# openssl x509 -in /etc/pki/tls/certs/controlplane.site1.example.com.pem -ext subjectAltName  -noout

