- name: add records to zones
  hosts: gateway
  become: true
  gather_facts: false
  serial: 1
  vars_files:
    - vault-credentials.yml
  roles:
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/configuring-static-routes_configuring-and-managing-networking#proc_configuring-a-static-route-by-using-the-network-rhel-system-role_configuring-static-routes
    - name: route to host2 where core services are
      role: rhel-system-roles.network
      vars:
        network_connections:
          - name: enp1s0
            type: ethernet
            autoconnect: true
            state: up
            ip:
              route:
                - network: 192.168.135.0
                  prefix: 24
                  gateway: 192.168.1.135
