---

# accounts
user_ansible_password: Password;1

# network
# MAC addresses are listed here.
#   https://hardiman.consulting/rhel/9/unsorted/host1-libvirt-network.html
#
public_net_short_name: public
public_libvirt_name: "net{{ public_net_short_name }}0"
public_mac_prefix: "52:54:00:03"
public_nmcli_name: "bridge-{{ public_net_short_name }}0"
public_bridge_name: "br{{ public_net_short_name }}0"
#
lab_net_short_name: site1
lab_libvirt_name: "net{{ lab_net_short_name }}0"
lab_net_prefix: "192.168.136"
lab_mac_prefix: "52:54:00:04"
lab_domain: site1.lab.example.com
lab_reverse_zone: "136.168.192.in-addr.arpa"
#
# !!! duplicates. defined here and in host_vars
# to list keys of this dict of dicts in a loop, use: 
#       loop: "{{ address | list }}"
# address:
#   gateway:
#     mac: "{{ lab_mac_prefix }}:00:03"
#     ip_last_octet: "3"
#     ipv4: "{{ lab_net_prefix + '.3' }}"
#   controlplane-1:
#     mac: "{{ lab_mac_prefix }}:00:10"
#     ip_last_octet: "10"
#     ipv4: "{{ lab_net_prefix + '.10' }}"
#   controlplane-2:
#     mac: "{{ lab_mac_prefix }}:00:11"
#     ip_last_octet: "10"
#     ipv4: "{{ lab_net_prefix + '.11' }}"

# !!! TBC
# https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index#network_requirements
