---
# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
# https://blog.scheib.me/2023/07/09/automating-satellite.html


# https://github.com/sscheib/ansible_satellite/blob/main/host_vars/satellite.office.int.scheib.me/11b_content_views.yml
# https://satellite/ > Content > Lifecycle > Content Views
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/content_views/
# 12
# https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/content_view_publish/
# 13
sat_content_views:
  # RHEL 6
  - name: 'cv-rhcdn-base-rhel-6'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    repositories:
      - name: Red Hat Enterprise Linux 6 Server RPMs x86_64 6Server
        product: Red Hat Enterprise Linux Server

      - name: Red Hat Enterprise Linux 6 Server - Extras RPMs x86_64
        product: Red Hat Enterprise Linux Server

      - name: Red Hat Enterprise Linux 6 Server - Optional RPMs x86_64
        product: Red Hat Enterprise Linux Server

      - name: Red Hat Enterprise Linux 6 Server Kickstart x86_64 6.10
        product: Red Hat Enterprise Linux Server
        
  # RHEL 7
  - name: 'cv-rhcdn-base-rhel-7'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    repositories:
      - name: Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server 
        product: Red Hat Enterprise Linux Server
        
      - name: Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64
        product: Red Hat Enterprise Linux Server
        
      - name: Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9
        product: Red Hat Enterprise Linux Server

  # RHEL 8
  - name: 'cv-rhcdn-base-rhel-8'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    repositories:
        # no lifecycle_environments list - publish to all lifecycle envs
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.8'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-satellite_6_client-rhel-8'
    repositories:
      - name: 'Red Hat Satellite Client 6 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'

    # empty lifecycle_environments list - publish to no lifecycle envs
  - name: 'cv-rhcdn-ansible_automation_platform-rhel-8'
    lifecycle_environments: []
    repositories:
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 8 x86_64 RPMs'
        product: 'Red Hat Ansible Automation Platform'

  # RHEL 9
  - name: 'cv-rhcdn-base-rhel-9'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.4'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream Kickstart 9.4'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-satellite_6_client-rhel-9'
    repositories:
      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'

  - name: 'cv-rhcdn-ansible_automation_platform-rhel-9'
    lifecycle_environments: []
    repositories:
      - name: 'Red Hat Ansible Automation Platform 2.4 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Ansible Automation Platform'

# IPU
# InPlace Upgrade using leapp via Satellite webUI - rhel7 to rhel8
# https://www.youtube.com/watch?v=9ZA3JyJHL8s
  - name: 'cv-leapp'
    lifecycle_environments: []
    repositories:
      - name: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'

      - name: 'Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8'
        product: 'Red Hat Enterprise Linux for x86_64'


# https://github.com/sscheib/ansible_satellite/blob/main/host_vars/satellite.office.int.scheib.me/11a_content_views_custom_products.yml
# Define Content Views that contain custom Products
sat_content_views_custom_products:
  - name: 'cv-elastic-elastic-el-8'
    repositories:
      - name: 'repo-elastic-elastic-8-el-8'
        product: 'prd-elastic-elastic'

  - name: 'cv-zabbix-zabbix-rhel-8'
    repositories:
      - name: 'repo-zabbix-zabbix-6_0-rhel-8'
        product: 'prd-zabbix-zabbix'

  - name: 'cv-zabbix-zabbix-rhel-9'
    repositories:
      - name: 'repo-zabbix-zabbix-6_0-rhel-9'
        product: 'prd-zabbix-zabbix'


# https://github.com/sscheib/ansible_satellite/blob/main/host_vars/satellite.office.int.scheib.me/11c_composite_content_views.yml
# 
sat_composite_content_views:
  - name: 'ccv-default-rhel-8'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-8'
        latest: true

      - content_view: 'cv-elastic-elastic-el-8'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-8'
        latest: true

  - name: 'ccv-default-rhel-9'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-9'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-9'
        latest: true

  - name: 'ccv-ansible_automation_platform-rhel-8'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-ansible_automation_platform-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-8'
        latest: true

      - content_view: 'cv-elastic-elastic-el-8'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-8'
        latest: true

  - name: 'ccv-ansible_automation_platform-rhel-9'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-ansible_automation_platform-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-9'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-9'
        latest: true


# Combine the Content Views of custom Products, the Content Views of Red Hat Products and the Composite Content Views
satellite_content_views: '{{ sat_content_views +
                             sat_content_views_custom_products +
                             sat_composite_content_views }}'

