---
# vars file for AAP controller

# see "Organization Data Structure" here.
# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/organizations/
# 3 organizations
controller_organizations:
  - name: org1
    description: Organization 1
    galaxy_credentials:
      - Ansible Galaxy
  - name: org2
    description: Organization 2
    galaxy_credentials:
      - Ansible Galaxy
  - name: org3
    description: Organization 3
    galaxy_credentials:
      - Ansible Galaxy

# 3 teams per organization, 9 teams
controller_teams:
  - name: o1team1
    organization: org1
  - name: o1team2
    organization: org1
  - name: o1team3
    organization: org1
  - name: o2team1
    organization: org2
  - name: o2team2
    organization: org2
  - name: o2team3
    organization: org2
  - name: o3team1
    organization: org3
  - name: o3team2
    organization: org3
  - name: o3team3
    organization: org3

# 3 people per team, 27 user accounts
controller_user_accounts:
# org1
  - user: o1t1user1
    password: redhat
  - user: o1t1user2
    password: redhat
  - user: o1t1user3
    password: redhat
  - user: o1t2user1
    password: redhat
  - user: o1t2user2
    password: redhat
  - user: o1t2user3
    password: redhat
  - user: o1t3user1
    password: redhat
  - user: o1t3user2
    password: redhat
  - user: o1t3user3
    password: redhat
# org2
  - user: o2t1user1
    password: redhat
  - user: o2t1user2
    password: redhat
  - user: o2t1user3
    password: redhat
  - user: o2t2user1
    password: redhat
  - user: o2t2user2
    password: redhat
  - user: o2t2user3
    password: redhat
  - user: o2t3user1
    password: redhat
  - user: o2t3user2
    password: redhat
  - user: o2t3user3
    password: redhat
# org3
  - user: o3t1user1
    password: redhat
  - user: o3t1user2
    password: redhat
  - user: o3t1user3
    password: redhat
  - user: o3t2user1
    password: redhat
  - user: o3t2user2
    password: redhat
  - user: o3t2user3
    password: redhat
  - user: o3t3user1
    password: redhat
  - user: o3t3user2
    password: redhat
  - user: o3t3user3
    password: redhat

# examples from book "Demystifying Ansible Automation Platform"
# https://github.com/PacktPublishing/Demystifying-Ansible-Automation-Platform

# controller_user_accounts:
#   - user: joe_123
#     is_superuser: false
#     password: password123
    
# controller_teams:
#   - name: Joes
#     organization: Default

# controller_roles:
#   - user:  joe_123
#     team: Joes
#     role: member