---
# vars file for AAP controller

# credentials

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/credentials/
# Each credential type has input fields, described in each API page. 
# The "machine" credential type is assigned ID 1, SCM is 2, vault is 3, etc. 
# https://controlplane-site1.home/api/v2/credential_types/1/
controller_credentials:
  - name: o1_gitlab
    description: org1's credentials for GitLab, created by Ansible Playbook
    organization: org1
    credential_type: Source Control
    inputs:
      username: person
      password: password
  - name: o1_ansible_user
    description: org1's Ansible user, created by Ansible Playbook
    credential_type: Machine
    organization: org1
    inputs:
      username: "{{ user_ansible_name }}"
      ssh_key_data: "{{ user_ansible_private_key}}"
      # become_method: sudo

# inventories

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/inventories/
controller_inventories:
  - name: o1_inv1
    description: inventory for org1
    organization: org1
    variables:
      inventory_var: inventory_value
    state: present
  - name: o2inv1
    description: inventory for org2
    organization: org2
  - name: o3inv1
    description: inventory for org3
    organization: org3

# hosts

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/hosts/
controller_hosts:
  - name: o1host1
    inventory: o1_inv1
    variables:
      hosts_var: some_val
      ansible_connection: local
    enabled: true
    state: present
  - name: o1host2
    inventory: o1_inv1
  - name: o1host3
    inventory: o1_inv1
  - name: o2host1
    inventory: o2inv1
  - name: o3host1
    inventory: o3inv1

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/groups/
controller_groups:
  - name: o1group1
    inventory: o1_inv1
    variables:
      groups_variable: group_val
    hosts:
      - o1host1
      - o1host2
    children:
      - o1group1_child
    state: present
  - name: o1group1_child
    inventory: o1_inv1
    hosts:
      - o1host3


# projects

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/projects/
controller_projects:
  - name: o1_public_project
    scm_type: git
    scm_url: https://github.com/ansible/test-playbooks.git
    # scm_url: https://github.com/ansible/ansible-tower-samples
    # scm_url: https://github.com/ansible/tower-example.git
    # scm_url: https://github.com/ansible/ansible-examples.git
    scm_branch: master
    scm_clean: true
    description: org1's project sourced from a public github repo
    organization: org1
    wait: true
    update_project: true
  - name: o1_private_project
    scm_type: git
    scm_url: https://gitlab.site3.example.com/ansible/test-playbooks.git
    # scm_branch: master
    credential: o1_gitlab
    description: org1's project sourced from a private gitlab repo
    organization: org1
    update_project: false
  - name: o1_misc_project
    scm_type: git
    scm_url: https://github.com/nickhardiman/misc
    description: project sourced from Nick's public github repo
    organization: org1


# templates

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/job_templates/
# No field "organization" for job templates.
controller_templates:
  - 
    name: o1_test_template
    description: org1's test template, created by Ansible Playbook
    job_type: run
    inventory: o1_inv1
    credentials:
      - o1_ansible_user
    project: o1_public_project
    playbook: chatty_payload.yml
    verbosity: 2
    extra_vars:
      target_hosts: controlplane-1.site1.example.com
  - 
    name: o1_misc_template_check_before
    description: part of org1's misc workflow
    job_type: run
    inventory: o1_inv1
    credentials:
      - o1_ansible_user
    project: o1_misc_project
    playbook: ansible/workflow/check-before.yml
  - 
    name: o1_misc_template_do_thing
    description: part of org1's misc workflow
    job_type: run
    inventory: o1_inv1
    credentials:
      - o1_ansible_user
    project: o1_misc_project
    playbook: ansible/workflow/do-thing.yml
  - 
    name: o1_misc_template_check_after
    description: part of org1's misc workflow
    job_type: run
    inventory: o1_inv1
    credentials:
      - o1_ansible_user
    project: o1_misc_project
    playbook: ansible/workflow/check-after.yml

# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/workflow_job_templates/
controller_workflows:
  - name: o1_misc_workflow
    description: A basic workflow schema example
    ask_inventory_on_launch: false
    organization: org1
    simplified_workflow_nodes:
      - 
        identifier: check_before
        unified_job_template: o1_misc_template_check_before
        success_nodes:
          - do_thing
        failure_nodes: []
        always_nodes: []
      - 
        identifier: do_thing
        unified_job_template: o1_misc_template_do_thing
        success_nodes:
          - check_after
        failure_nodes: []
        always_nodes: []
      - 
        identifier: check_after
        unified_job_template: o1_misc_template_check_after
        success_nodes: []
        failure_nodes: []
        always_nodes: []
