---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 
# default 2 cores
# default 4GiB memory

# storage
# default 30GB disk

# network
nics:
- 
  name: enp1s0
  mac: "{{ site1_mac_prefix }}:00:10"
  net: "{{ site1_libvirt_name }}"
  # !!! get rid of this?
  # used in 
  # ansible_collections/nick/platform/roles/hosts_record/tasks/main.yml
  # IP from DHCP
  ip: "{{ site1_net_prefix }}.10"

net_services:
- http
- https
- ssh

# OS
host: controlplane-1
fqdn: "{{ host }}.site1.lab.example.com"
RPMs: {}
#install_iso: /var/lib/libvirt/images/rhel-8.6-x86_64-dvd.iso
#os_variant: rhel8.5

# kickstart
kickstart_template: "kvm-guest.ks.j2"

# accounts
