---
# virt-install

# compute 
# double the default
# half what is recommended by 
# https://access.redhat.com/documentation/en-us/reference_architectures/2021/html-single/deploying_ansible_automation_platform_2.1/index#node_requirements
cpus: 4
ram: 8192

# storage
# default 30GB disk

# network
last_octet: 16
nics:
  -
    name: enp1s0
    mac: "{{ lab_mac_prefix }}:00:{{ last_octet }}"
    net: "{{ lab_libvirt_name }}"
    ip: "{{ lab_net_prefix }}.{{ last_octet }}"

net_services:
  - http
  - https
  - ssh

# OS
host: executionnode-2
fqdn: "{{ host }}.{{ lab_domain }}"
RPMs: 
  - python3-cryptography

# kickstart
kickstart_template: "kvm-guest-static.ks.j2"

# accounts
