---
# group vars for site1

# network
# Names and addresses are partially set in variables below.
# A full list is here.
#   https://github.com/nickhardiman/ansible-playbook-aap2-refarch/tree/main
# For the remaining parts of these names and addresses, see each host's vars file eg.
#   host_vars/gateway.site1.example.com/main.yml
# Note the suffix "." on domain names.
#
# nework identifiers
# 20 - site1 public 
# 21 - site1 private 
# 22 - site2 public 
# 23 - site2 private 
# 24 - site3 public 
# 25 - site3 private 

public_net_short_name: public
public_libvirt_name:   "net{{ public_net_short_name }}0"
public_mac_prefix:     "52:54:00:20"
public_nmcli_name:     "bridge-{{ public_net_short_name }}0"
public_bridge_name:    "br{{ public_net_short_name }}0"

lab_net_short_name:    site1
lab_net_prefix:        "192.168.21"
lab_mac_prefix:        "52:54:00:21"
lab_libvirt_name:   "net{{ lab_net_short_name }}0"
lab_nmcli_name: "bridge-{{ lab_net_short_name }}0"
lab_bridge_name:     "br{{ lab_net_short_name }}0"
lab_bridge_mac:        "{{ lab_mac_prefix }}:00:01"
lab_bridge_ip_cidr:    "{{ lab_net_prefix }}.1/24"
lab_domain:            "{{ lab_net_short_name }}.example.com"
# DNS Zone names in IPA Server
lab_domain_forward:    "{{ lab_net_short_name }}.example.com"
# Satellite does not handle the trailing full stop/period/dot ".".
# lab_domain_reverse:    "21.168.192.in-addr.arpa."
lab_domain_reverse:    "21.168.192.in-addr.arpa"

# proxy
# useful for
# RHSM registration. see https://github.com/nickhardiman/ansible-collection-aap2-refarch/blob/main/roles/register_rhsm/tasks/main.yml
# package downloads
server_proxy_hostname: "gateway.{{ lab_domain }}"
server_proxy_port: 3128
