---
# virt-install
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# compute 

# storage
# default 30GB disk

# network
last_octet: 17
nics:
  -
    name: enp1s0
    mac: "{{ lab_mac_prefix }}:00:{{ last_octet }}"
    net: "{{ lab_libvirt_name }}"
    # !!! get rid of this?
    # IP from DHCP
    ip: "{{ lab_net_prefix }}.{{ last_octet }}"

net_services:
  - http
  - https
  - ssh

server_proxy_hostname: gateway.site1.lab.example.com
server_proxy_port: 3128

# OS
host: automationhub-1
fqdn: "{{ host }}.site1.lab.example.com"
RPMs: 
  - python3-cryptography

# kickstart
kickstart_template: "kvm-guest-static.ks.j2"

# accounts
