---
# reference
# https://galaxy.ansible.com/ui/repo/published/infra/ah_configuration/content/role/group/

- name: Add users and groups to hub
  hosts: install_host
  gather_facts: true
  become: true
  vars_files:
    - ~/vault-credentials.yml

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: aap-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  roles:
    - infra.ah_configuration.group
    - infra.ah_configuration.role
    - infra.ah_configuration.group_roles
    - infra.ah_configuration.user
