---
# see aap-controller-settings.yml for more proxy config
- name: Make AAP play nice with a reverse proxy
  hosts: automationcontroller_site1
  gather_facts: true
  become: true
  vars_files:
    - ~/vault-credentials.yml

  tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: aap-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
    
    - name: Add lines to /etc/tower/conf.d/custom.py
      vars:
        xff_config: |
          USE_X_FORWARDED_PORT = True
          USE_X_FORWARDED_HOST = True
      ansible.builtin.copy:
        content: "{{ xff_config }}"
        dest: /etc/tower/conf.d/custom.py

    - name: Restart AAP controller? Is this necessary?
      ansible.builtin.systemd_service:
        name: automation-controller.service
        state: restarted
        enabled: true
