---
# reference
# collection "infra.controller_configuration"
# https://galaxy.ansible.com/ui/repo/published/infra/controller_configuration/content/role/organizations/
# controller API
# https://developers.redhat.com/api-catalog/api/ansible-automation-controller
# run 
#   ansible-playbook   --vault-pass-file ~/my-vault-pass  playbooks/aap-controller-access.yml 
# debug
#   ansible-playbook \
#     --vault-pass-file ~/my-vault-pass  \
#     --extra-vars='controller_configuration_group_secure_logging=false' \
#     --extra-vars='controller_configuration_users_secure_logging=false' \
#     --verbose \
#     playbooks/aap-controller-access.yml 

- name: Add organizations, users and teams to controller
  hosts: install_host
  gather_facts: true
  become: true
  vars_files:
    - ~/vault-credentials.yml

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: aap-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  roles:
    # - infra.controller_configuration.organizations
    # - infra.controller_configuration.users
    # - infra.controller_configuration.teams
    - infra.controller_configuration.roles
