---
# create_organization_using_role.yml
- name: Playbook to push organizations to controller
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ~/vault-credentials.yml
  # pre_tasks:
  #   - name: Create Organization
  #     ansible.controller.organization:
  #       controller_host: controlplane.site1.example.com
  #       controller_username: admin
  #       controller_password: "{{ default_password }}"
  #       name: Satellite_org
  roles:
    - role: infra.controller_configuration.organizations
      vars:
        # "controller_host" above and "controller_hostname" here
        controller_hostname: controlplane.site1.example.com
        controller_username: admin
        controller_password: "{{ default_password }}"
        controller_organizations:
          - name: Satellite
            description: My Satellite
...
