---
# create_organization_using_role.yml
- name: Playbook to push organizations to controller
  hosts: localhost
  connection: local
  vars:
    controller_host: controlplane.site1.example.com
    controller_username: admin
    controller_password: "{{ default_password }}"
    controller_organizations:
      - name: Satellite
      - name: Default
  vars_files:
    - ~/vault-credentials.yml
  roles:
    - infra.controller_configuration.organizations
...