- name: Distribute /etc/hosts file from install host to all hosts
  hosts: all:!install_host
  become: true
  gather_facts: false
  vars_files:
    - ~/vault-credentials.yml
  #
  roles:
    - role: nick.platform.hosts_file

