---
# copy /etc/hosts to all VMs, except for 
# * the install host (the source of the file)
# * private interfaces of the gateways (use the public interfaces instead)
- name: Distribute /etc/hosts file from install host to all hosts
  hosts: all:!install_host:!gateway_lab
  become: true
  gather_facts: false
  vars_files:
    - ~/vault-credentials.yml
  #
  roles:
    - role: nick.platform.hosts_file

