---
- ansible.builtin.import_playbook: machine-hypervisor.yml

- ansible.builtin.import_playbook: vm-kickstart.yml
- ansible.builtin.import_playbook: vm-hosts.yml
- ansible.builtin.import_playbook: vm-start.yml

- ansible.builtin.import_playbook: roles-gateway_home.yml
- ansible.builtin.import_playbook: roles-vm.yml
