---
- ansible.builtin.import_playbook: machine-hypervisor.yml

- ansible.builtin.import_playbook: vm-kickstart.yml
- ansible.builtin.import_playbook: etc-hosts-gateways.yml
- ansible.builtin.import_playbook: etc-hosts-other-vms.yml
- ansible.builtin.import_playbook: etc-hosts-load-balancers.yml
- ansible.builtin.import_playbook: vm-start.yml

- ansible.builtin.import_playbook: configure-gateways.yml
- ansible.builtin.import_playbook: configure-vms.yml
- ansible.builtin.import_playbook: configure-hub.yml

- ansible.builtin.import_playbook: aap-install.yml
- ansible.builtin.import_playbook: aap-manifest.yml
- ansible.builtin.import_playbook: aap-controller-proxy.yml
- ansible.builtin.import_playbook: aap-controller-access.yml
- ansible.builtin.import_playbook: aap-controller-resources.yml
- ansible.builtin.import_playbook: aap-hub-access.yml

# !!! todo
# - ansible.builtin.import_playbook: vm-to-template.yml
# - ansible.builtin.import_playbook: template-to-vm.yml

