---
- name: Import playbooks to make a great big list of all plays
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: One play to rule them all

# physical machine OS layer
- ansible.builtin.import_playbook: machine-hypervisor.yml
- ansible.builtin.import_playbook: machine-os.yml
- ansible.builtin.import_playbook: machine-network.yml

# virtual machine layer
- ansible.builtin.import_playbook: vm-kickstart.yml
- ansible.builtin.import_playbook: etc-hosts-gateways.yml
- ansible.builtin.import_playbook: etc-hosts-other-vms.yml
- ansible.builtin.import_playbook: etc-hosts-load-balancers.yml
- ansible.builtin.import_playbook: vm-start.yml

# virtual machine OS layer
- ansible.builtin.import_playbook: configure-gateways.yml
- ansible.builtin.import_playbook: configure-vms.yml
- ansible.builtin.import_playbook: configure-hub.yml

# virtual machine application layer

# install and configure AAP 
- ansible.builtin.import_playbook: aap-install-installer.yml
- ansible.builtin.import_playbook: aap-install-certs.yml
#
# site1
- ansible.builtin.import_playbook: aap-install-site1.yml
# CaC playbooks 
- ansible.builtin.import_playbook: aap-manifest.yml
- ansible.builtin.import_playbook: aap-controller-settings.yml
- ansible.builtin.import_playbook: aap-controller-proxy.yml
- ansible.builtin.import_playbook: aap-controller-access.yml
- ansible.builtin.import_playbook: aap-controller-resources.yml
- ansible.builtin.import_playbook: aap-hub-access.yml
- ansible.builtin.import_playbook: aap-hub-collections.yml
- ansible.builtin.import_playbook: aap-hub-execution-environments.yml
- ansible.builtin.import_playbook: aap-controller-execution-environments.yml
#
# site2
- ansible.builtin.import_playbook: aap-install-site2.yml
# The CaC playbooks are identical to site1 except:  
# * controller_hostname
# * ah_host
# !!! perhaps 
# - ansible.builtin.import_playbook: aap-changes-for-site2.yml
# - ansible.builtin.import_playbook: aap-manifest.yml
# - ansible.builtin.import_playbook: aap-controller-settings.yml
# ...
# or
# - ansible.builtin.import_playbook: aap-manifest.yml
#   vars:
#     controller_hostname: controlplane.site2.example.com
#     ah_host: automationhub.site2.example.com
# - ansible.builtin.import_playbook: aap-controller-settings.yml
#   vars:
#     controller_hostname: controlplane.site2.example.com
#     ah_host: automationhub.site2.example.com
# ...

# install and configure OS and application layers on site3

# !!! todo
# - ansible.builtin.import_playbook: vm-to-template.yml
# - ansible.builtin.import_playbook: template-to-vm.yml

