---
- ansible.builtin.import_playbook: machine-hypervisor.yml

- ansible.builtin.import_playbook: vm-kickstart.yml
- ansible.builtin.import_playbook: etc-hosts-gateways.yml
- ansible.builtin.import_playbook: etc-hosts-other-vms.yml
- ansible.builtin.import_playbook: etc-hosts-load-balancers.yml
- ansible.builtin.import_playbook: vm-start.yml

- ansible.builtin.import_playbook: configure-gateways.yml
- ansible.builtin.import_playbook: configure-vms.yml
- ansible.builtin.import_playbook: configure-nfs.yml

- ansible.builtin.import_playbook: app-aap-install.yml
- ansible.builtin.import_playbook: app-aap-configure.yml

# !!! todo
# - ansible.builtin.import_playbook: vm-to-template.yml
# - ansible.builtin.import_playbook: template-to-vm.yml

