---
- ansible.builtin.import_playbook: machine-hypervisor.yml

- ansible.builtin.import_playbook: vm-kickstart.yml
- ansible.builtin.import_playbook: vm-hosts.yml
- ansible.builtin.import_playbook: vm-start.yml

- ansible.builtin.import_playbook: roles-gateway_home.yml
- ansible.builtin.import_playbook: roles-vm.yml

# !!! todo
# - ansible.builtin.import_playbook: vm-to-template.yml
# - ansible.builtin.import_playbook: template-to-vm.yml

- ansible.builtin.import_playbook: app-aap-install.yml
- ansible.builtin.import_playbook: app-aap-configure.yml
