# !!! broken
# If there is no base file, assume configuration didn't complete and 
# we are good to go again.

# !!! move to building one VM template, 
# repeating this 20 times is pointless

- name: Configure new server machine
  hosts: vm:!gateway
  become: true
  gather_facts: false
  serial: 1
  vars_files:
    - ~/vault-credentials.yml
  environment:
    http_proxy:  "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
    HTTPS_PROXY: "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
    no_proxy: localhost,127.0.0.1,example.com

  roles:
    - role: nick.platform.managed_node
    - role: nick.platform.hosts_file
    - role: nick.platform.dns_client_of_gateway
    - role: nick.platform.register_rhsm
    - role: nick.platform.latest_packages
    - role: nick.platform.server_cert
    - role: nick.platform.smtp_client
    - role: nick.platform.cockpit_server
    # !!! rhc installs insights on RHEL 7 onwards. 6? 
    # - role: nick.platform.register_insights
    - role: nick.platform.register_rhc
