# !!! broken
# If there is no base file, assume configuration didn't complete and 
# we are good to go again.

# !!! move to building one VM template, 
# repeating this 20 times is pointless

- name: Configure new server machine
  hosts: vm:!gateway
  become: true
  gather_facts: false
  serial: 1
  vars_files:
    - ~/vault-credentials.yml
  environment:
    http_proxy: "http://gateway.{{ lab_domain }}:3128"
    HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
    no_proxy: localhost,127.0.0.1,example.com
  #
  roles:
    - role: nick.platform.managed_node
    - role: nick.platform.hosts_file
    - role: nick.platform.cdn_repo_consumer
    - role: nick.platform.latest_packages
    - role: nick.platform.server_cert
    - role: nick.platform.smtp_client
    - role: nick.platform.cockpit_server
    - role: nick.platform.insights_client

