---
# !!! move to collection roles

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
# https://blog.scheib.me/2023/07/09/automating-satellite.html

# !!! todo 
#
# add hostgroup parameter remote_execution_ssh_keys
# add parameter remote_execution_ssh_user for root user
# for foreman_proxy key and ansible_user?
# for "Kickstart finish" provisioning template snippet "remote_execution_ssh_keys"
#
# create libvirt compute resource
# create libvirt compute resource compute profiles
#
# change compute profile CPU mode from default to host-model
# causes rhel 9 provision kernel panic 
#
# change compute profile memory to at least 3096GB
# https://access.redhat.com/solutions/6958349
# Red Hat Satellite Provisioning a RHEL 8.6 system fails with `dracut-initqueue: /lib/dracut-lib.sh: echo: write error: No space left on device
#
# host.build.example.com to id DNS
#
# fix activation key fail
#
# create host collections rhel-8 and rhel-9
# associate with activation keys
#
# add cockpit console to Satellite
# https://www.redhat.com/sysadmin/rhel-web-console-satellite
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html-single/managing_hosts/index#Host_Management_and_Monitoring_Using_Cockpit_managing-hosts
#
# enable Satellite Client 6 repository 
# install tracer 
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.13/html-single/managing_hosts/index#enabling-tracer-on-a-host_managing-hosts
#
# add ccv- composite content views for baseos, appstream and sat client
# change hg- host groups to use ccv-
#   
# Add a KVM connection to Satellite Server
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.15/html-single/provisioning_hosts/index#configuring-server-for-kvm-connections_kvm-provisioning


- name: Satellite config for the Infrastructure section of the web UI 
  hosts: satellite.site3.example.com
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true  # required for the role redhat.satellite_operations.installer
  vars_files:
    - ~/vault-credentials.yml
  # environment:
  #   http_proxy: "http://gateway.{{ lab_domain }}:3128"
  #   HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
  #   no_proxy: localhost,127.0.0.1,example.com

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: satellite-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  roles:

      # 10
    - role: redhat.satellite.domains
      # 11
    - role: redhat.satellite.subnets
