---

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite

- name: Define satellite's proxy to the internet 
  hosts: satellite.site3.example.com
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true        # required for the role redhat.satellite_operations.installer
  # vars_files:
  #   - ~/vault-credentials.yml
  # environment:
  #   http_proxy:  "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
  #   HTTPS_PROXY: "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
  #   no_proxy: localhost,127.0.0.1,example.com

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: satellite-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: Create proxy 'gateway'
      redhat.satellite.http_proxy:
        server_url: "{{ sat_server_url }}"
        username: "{{ sat_admin_user }}"
        password: "{{ sat_admin_pass }}"
        name: gateway
        url: "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
        locations:
          - "{{ sat_location }}"
        organizations:
          - "{{ sat_organization }}"
        state: present

  roles:
    - name: Configure default proxy 'gateway'
      role: redhat.satellite.settings
