---

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
# reference
# https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html-single/installing_satellite_server_in_a_connected_network_environment/index#configuring-repositories_satellite

- name: Install Red Hat Satellite
  hosts: satellite.site3.example.com
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true        # required for the role redhat.satellite_operations.installer
  vars_files:
    - ~/vault-credentials.yml

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: satellite-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: "Watch the log on {{ installer_hostname }}"
      ansible.builtin.debug:
        verbosity: 1
        msg: Installer messages are logged to /var/log/foreman-installer/satellite.log

    - name: Disable cockpit. It uses port 9090 which clashes with foreman-proxy.service
      ansible.builtin.systemd_service:
        name: cockpit.socket
        state: stopped
        enabled: false

  roles:
    # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite_operations/docs/
    - role: redhat.satellite_operations.installer

