---
# Add administration config to Red Hat Satellite.
# In the web UI, this is located in the the 'Administer' section of Satellite.

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite

# Products cannot be enabled without proxy to Red Hat's Content Delivery Network.
# When the manifest is imported, products appear.
# Satellite is behind a proxy.
# Without proxy settings, no repos will appear and cannot be enabled.

- name: Define satellite's proxy to the internet 
  hosts: satellite.site3.example.com
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true        # required for the role redhat.satellite_operations.installer
  vars_files:
    - ~/vault-credentials.yml
  # environment:
  #   http_proxy:  "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
  #   HTTPS_PROXY: "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
  #   no_proxy: localhost,127.0.0.1,example.com

  pre_tasks:

    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: satellite-vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: "Create proxy config 'gateway' for http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
      redhat.satellite.http_proxy:
        name: gateway
        url: "http://{{ server_proxy_hostname }}:{{ server_proxy_port }}"
        server_url:   "{{ satellite_server_url }}"
        username:     "{{ satellite_username }}"
        password:     "{{ satellite_password }}"
        organizations:
          - "{{ satellite_organization }}"
        locations:
          - "{{ satellite_location }}"
        state: present

  roles:
    - name: Configure default proxy 'gateway'
      role: redhat.satellite.settings
