---
# !!! convert from
#   hosts: "{{ host_to_image }}"
# to
#   hosts: hypervisor

- name: Start a new instance of the machine, and set to autostart
  hosts: "{{ host_to_start }}"
  become: true
  gather_facts: false
  serial: 1
  roles:
  - name: "Create a new instance"
    role: nick.platform.libvirt_machine_from_image
    delegate_to: "{{ groups['hypervisor'][0] }}"

  tasks:

    - name: Wait for new server to be ready
      ansible.builtin.wait_for_connection:
        timeout: 120
      become: false
