---
# Create a new virtual machine using libvirt.
# Install and configure the OS using a kickstart file.

# !!! create a single VM 
# is not overriding role defaults with host vars. 
# they have to be supplied on the CLI like this.
# ansible-playbook       \
#  --vault-pass-file ~/my-vault-pass  \
#  -v \
#  --inventory inventories/inventory-single-host.yml \
#  --extra-vars='install_iso=/var/lib/libvirt/images/rhel-8.10-x86_64-dvd.iso'  \
#  --extra-vars='os_variant=rhel8.10'  \
#  playbooks/vm-kickstart.yml


- name: Create a VM from an image
  hosts: hypervisor
  become: true
  gather_facts: false
  vars_files:
    - ~/vault-credentials.yml

  tasks:
    - name: Hosts to build
      ansible.builtin.set_fact:
        hosts_to_build: "{{ groups[hostvars[inventory_hostname]['vm_group']] }}"


    - name: "On hypervisor {{ inventory_hostname }}"
      ansible.builtin.include_role: 
        name: nickhardiman.hypervisor.libvirt_machine_from_image
      vars:
        fqdn: "{{ item }}"
        osinfo: "{{ hostvars[item]['osinfo'] | default('rhel7.9') }}"
      loop: "{{ hosts_to_build }}"
