---
# Most of these variables are for virt-install and OS kickstart.
# These values override defaults.
# default variables and their values are listed here. 
#   https://github.com/nickhardiman/libvirt-guest/blob/main/defaults/main.yml

# network
last_octet: 24
nics:
  -
    name: eth1
    mac: "{{ lab_mac_prefix }}:00:{{ last_octet }}"
    net: "{{ lab_libvirt_name }}"
    # !!! get rid of this?
    # IP from DHCP
    ip: "{{ lab_net_prefix }}.{{ last_octet }}"

net_services:
  - cockpit
  - http
  - https
  - ssh


# OS
host: misc-rhel6
fqdn: "{{ host }}.{{ lab_domain }}"
install_iso: /var/lib/libvirt/images/rhel-server-6.10-x86_64-dvd.iso
# Use this command to get the list of accepted OS variants.
#  virt-install --osinfo list
os_variant: rhel6.10
# extra RPM packages to add to the install list in
# https://github.com/nickhardiman/ansible-collection-aap2-refarch/blob/main/roles/libvirt_machine_kickstart/templates/kvm-guest-nic-static.ks.j2
RPMs: []
#
# RHSM registration. see
# https://github.com/nickhardiman/ansible-collection-aap2-refarch/blob/main/roles/register_rhsm/tasks/main.yml
server_proxy_hostname: "gateway.{{ lab_domain }}"
server_proxy_port: 3128

# kickstart
# !!! does not work with RHEL 6 or 7
kickstart_template: "kvm-guest-nic-static.ks.j2"
